name: ghereass

description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.0.5  # إدارة الحالة
  shared_preferences: ^2.2.2  # تخزين محلي
  async: ^2.11.0  # متوافقة مع flutter_test
  characters: ^1.3.0  # متوافقة مع flutter_test
  collection: ^1.19.0  # متوافقة مع flutter_test
  material_color_utilities: ^0.11.1  # متوافقة مع flutter_test
  meta: ^1.15.0  # متوافقة مع flutter_test
  path: ^1.9.0  # متوافقة مع flutter_test
  source_span: 1.10.0  # تخفيض لمطابقة flutter_test
  string_scanner: 1.3.0  # تخفيض لمطابقة flutter_test
  term_glyph: 1.2.1  # تخفيض لمطابقة flutter_test
  image_picker: ^1.0.7  # لاختيار الصور
  google_maps_flutter: ^2.5.0  # لتحديد الموقع من الخريطة
  intl: ^0.18.1
  file_picker: ^6.1.1 # لاختيار الملفات (PDF)
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/gherass.png  # تأكد من وجود الصورة في هذا المسار الصحيح
