name: gherass
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animated_rating_stars: ^1.0.1
  permission_handler: ^11.0.0
  cloud_firestore: ^5.6.5
  custom_sliding_segmented_control: ^1.8.5
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  file_picker: ^9.0.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_storage: ^2.0.3
  image_picker: ^1.1.2
  toastification: ^3.0.2
  time_range_picker: ^2.3.0
  persistent_bottom_nav_bar: ^6.2.1
  dots_indicator: ^4.0.1
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  intl: 0.19.0
  url_launcher: ^6.3.1
  adoptive_calendar: ^0.2.0
  http: ^1.3.0
  googleapis_auth: ^1.3.1
  flutter_rating: ^2.0.2

  cupertino_icons: ^1.0.8
  text_scroll: ^0.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/fcm_key.json
