// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiNQeqVQGIWB1Bs1gxugexjYM5xAlAFNU',
    appId: '1:351272618438:android:eced0103907115715ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeN8BwQGlaGwZbYwtZGeuk8Soy76dbbiw',
    appId: '1:351272618438:ios:613eb975843295605ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    androidClientId: '351272618438-m30ittg9n2sq65hu8avuuptunr2plk5o.apps.googleusercontent.com',
    iosClientId: '351272618438-ct9p8sosa224kl1ia73eog64m1b62pfe.apps.googleusercontent.com',
    iosBundleId: 'com.leadergroup.gherass.gherass',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsYvvRRFhUk-Ei_Et8nVq0FR5c5jIN4w',
    appId: '1:351272618438:web:5dee56beb9ddf8dc5ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    authDomain: 'gherass-adc21.firebaseapp.com',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    measurementId: 'G-Q4LCSR1FY4',
  );
}