// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsYvvRRFhUk-Ei_Et8nVq0FR5c5jIN4w',
    appId: '1:351272618438:web:5dee56beb9ddf8dc5ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    authDomain: 'gherass-adc21.firebaseapp.com',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    measurementId: 'G-Q4LCSR1FY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiNQeqVQGIWB1Bs1gxugexjYM5xAlAFNU',
    appId: '1:351272618438:android:46e9970109b2b85d5ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeN8BwQGlaGwZbYwtZGeuk8Soy76dbbiw',
    appId: '1:351272618438:ios:cef23309053acac65ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    androidClientId: '351272618438-m30ittg9n2sq65hu8avuuptunr2plk5o.apps.googleusercontent.com',
    iosClientId: '351272618438-e4iph4kdoedj8g1c49csm8f7fpq05cvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghereass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeN8BwQGlaGwZbYwtZGeuk8Soy76dbbiw',
    appId: '1:351272618438:ios:cef23309053acac65ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    androidClientId: '351272618438-m30ittg9n2sq65hu8avuuptunr2plk5o.apps.googleusercontent.com',
    iosClientId: '351272618438-e4iph4kdoedj8g1c49csm8f7fpq05cvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghereass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCsYvvRRFhUk-Ei_Et8nVq0FR5c5jIN4w',
    appId: '1:351272618438:web:fdc5d7ddee325a395ecac7',
    messagingSenderId: '351272618438',
    projectId: 'gherass-adc21',
    authDomain: 'gherass-adc21.firebaseapp.com',
    databaseURL: 'https://gherass-adc21-default-rtdb.firebaseio.com',
    storageBucket: 'gherass-adc21.firebasestorage.app',
    measurementId: 'G-2QLEPNHCBK',
  );
}
